### ISSUE TITLE
java sample

### ISSUE THREAD

**Issue by jukinhaum** [hypeapps/MaterialTimelineView#4]
Hi there! i know that kotlin will replace java for android apps and stuff, but i still struggling with this language i just want to ask you if, theres a way to have a sample in java?

**Comment by hypeapps** [comment]
@jukinhaum 
There is an option. In Android Studio, you just have to do the following to get java code from kotlin:
1. Menu > Tools > Kotlin > Show Kotlin Bytecode
2. Click on the Decompile button
3. Copy the java code
