### ISSUE TITLE
Constants have private access

### ISSUE THREAD

**Issue by kwon0408** [hypeapps/MaterialTimelineView#6]
When trying to programmatically create an item in Java code, some constants like `MaterialTimelineView.TIMELINE_TYPE_ITEM` are needed to use but Android Studio says `TIMELINE_TYPE_ITEM has private access in 'pl.hypeapp.materialtimelineview.MaterialTimelineView'`. Is this intended or just a mistake?

**Comment by hypeapps** [comment]
Hi @kwon0408 
MaterialTimelineView defines these constants in companion object. More info: [Static Methods Kotlinlang docs](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html#static-methods)

You can get these constant like this:
`MaterialTimelineView.Companion.getTIMELINE_TYPE_LINE();`

I could add `@JvmStatic`  annotation above the fields. I will do this in version 1.2 so the constants will be accessible as usual.

**Comment by kwon0408** [comment]
Thank you, that was so helpful.
Closing this issue.
